from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName('MainWindow')
        MainWindow.resize(652, 402)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(652, 402))
        MainWindow.setMaximumSize(QtCore.QSize(652, 402))
        MainWindow.setWindowTitle('MarkE5per')
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 651, 371))

        self.tab_1 = QtWidgets.QWidget()
        self.listWidget = QtWidgets.QListWidget(self.tab_1)
        self.listWidget.setGeometry(QtCore.QRect(0, 0, 321, 331))
        self.listWidget_2 = QtWidgets.QListWidget(self.tab_1)
        self.listWidget_2.setGeometry(QtCore.QRect(330, 0, 311, 151))
        #self.saveButton = QtWidgets.QPushButton(self.tab_1)
        #self.saveButton.setGeometry(QtCore.QRect(555, 295, 84, 34))
        #self.saveButton.setText('Сохранить')

        self.fiveLabel = QtWidgets.QLabel(self.tab_1)
        self.fiveLabel.setGeometry(QtCore.QRect(330, 160, 16, 21))
        self.fiveLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.fiveLabel.setWordWrap(False)
        self.fiveLabel.setText('5')
        self.fourLabel = QtWidgets.QLabel(self.tab_1)
        self.fourLabel.setGeometry(QtCore.QRect(330, 190, 16, 21))
        self.fourLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.fourLabel.setWordWrap(False)
        self.fourLabel.setText('4')
        self.threeLabel = QtWidgets.QLabel(self.tab_1)
        self.threeLabel.setGeometry(QtCore.QRect(330, 220, 16, 21))
        self.threeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.threeLabel.setWordWrap(False)
        self.threeLabel.setText('3')
        self.averageLabel = QtWidgets.QLabel(self.tab_1)
        self.averageLabel.setGeometry(QtCore.QRect(330, 250, 311, 81))
        self.averageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.averageLabel.setWordWrap(False)
        self.rFiveLabel = QtWidgets.QLabel(self.tab_1)
        self.rFiveLabel.setGeometry(QtCore.QRect(530, 160, 101, 21))
        self.rFiveLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.rFiveLabel.setWordWrap(False)
        self.rFourLabel = QtWidgets.QLabel(self.tab_1)
        self.rFourLabel.setGeometry(QtCore.QRect(530, 190, 101, 21))
        self.rFourLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.rFourLabel.setWordWrap(False)
        #self.rThreeLabel = QtWidgets.QLabel(self.tab_1)
        #self.rThreeLabel.setGeometry(QtCore.QRect(530, 220, 101, 21))
        #self.rThreeLabel.setAlignment(QtCore.Qt.AlignCenter)
        #self.rThreeLabel.setWordWrap(False)
        self.fiveSlider = QtWidgets.QSlider(self.tab_1)
        self.fiveSlider.setGeometry(QtCore.QRect(350, 160, 131, 21))
        self.fiveSlider.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.fiveSlider.setAutoFillBackground(False)
        self.fiveSlider.setMaximum(10)
        self.fiveSlider.setPageStep(1)
        self.fiveSlider.setProperty('value', 0)
        self.fiveSlider.setOrientation(QtCore.Qt.Horizontal)
        self.fiveSlider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.fourSlider = QtWidgets.QSlider(self.tab_1)
        self.fourSlider.setGeometry(QtCore.QRect(350, 190, 131, 21))
        self.fourSlider.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.fourSlider.setAutoFillBackground(False)
        self.fourSlider.setMaximum(10)
        self.fourSlider.setPageStep(1)
        self.fourSlider.setProperty('value', 0)
        self.fourSlider.setOrientation(QtCore.Qt.Horizontal)
        self.fourSlider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.threeSlider = QtWidgets.QSlider(self.tab_1)
        self.threeSlider.setGeometry(QtCore.QRect(350, 220, 131, 21))
        self.threeSlider.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.threeSlider.setAutoFillBackground(False)
        self.threeSlider.setMaximum(10)
        self.threeSlider.setPageStep(1)
        self.threeSlider.setProperty('value', 0)
        self.threeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.threeSlider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.fiveSpinBox = QtWidgets.QSpinBox(self.tab_1)
        self.fiveSpinBox.setGeometry(QtCore.QRect(490, 160, 31, 21))
        self.fourSpinBox = QtWidgets.QSpinBox(self.tab_1)
        self.fourSpinBox.setGeometry(QtCore.QRect(490, 190, 31, 21))
        self.threeSpinBox = QtWidgets.QSpinBox(self.tab_1)
        self.threeSpinBox.setGeometry(QtCore.QRect(490, 220, 31, 21))
        self.tabWidget.addTab(self.tab_1, '')
        
        self.tab_2 = QtWidgets.QWidget()
        self.totalList = QtWidgets.QListWidget(self.tab_2)
        self.totalList.setGeometry(QtCore.QRect(0, 0, 321, 331))
        self.totalList_2 = QtWidgets.QListWidget(self.tab_2)
        self.totalList_2.setGeometry(QtCore.QRect(330, 0, 311, 331))
        self.tabWidget.addTab(self.tab_2, '')

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 650, 30))
        self.menu = QtWidgets.QMenu(self.menubar)
        MainWindow.setMenuBar(self.menubar)
        self.open = QtWidgets.QAction(MainWindow)
        self.settings = QtWidgets.QAction(MainWindow)
        self.last_opened = QtWidgets.QAction(MainWindow)
        self.about = QtWidgets.QAction(MainWindow)
        self.menu.addAction(self.open)
        self.menu.addAction(self.last_opened)
        self.menu.addSeparator()
        self.menu.addAction(self.settings)
        self.menu.addSeparator()
        self.menu.addAction(self.about)
        self.menubar.addAction(self.menu.menuAction())
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), 'Действия')
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), 'Итоги')
        self.menu.setTitle('Файл')
        self.open.setText('Открыть файл...')
        self.open.setShortcut('Ctrl+O')
        self.settings.setText('Настроить')
        self.last_opened.setText('Открыть последний')
        self.about.setText('О приложении')