from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Settings():
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(325, 402)
        Settings.setWindowTitle("Настройки")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Settings.sizePolicy().hasHeightForWidth())
        Settings.setSizePolicy(sizePolicy)
        Settings.setMinimumSize(QtCore.QSize(331, 411))
        Settings.setMaximumSize(QtCore.QSize(331, 411))
        self.buttonBox = QtWidgets.QDialogButtonBox(Settings)
        self.buttonBox.setGeometry(QtCore.QRect(120, 370, 201, 31))
        self.buttonBox.setToolTip("")
        self.buttonBox.setWhatsThis("")
        self.buttonBox.setAccessibleName("")
        self.buttonBox.setAccessibleDescription("")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        #self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Cancel)       
        self.button_apply = self.buttonBox.addButton(QtWidgets.QDialogButtonBox.Apply)
        self.button_cancel = self.buttonBox.addButton(QtWidgets.QDialogButtonBox.Cancel)
        self.buttonBox.setObjectName("buttonBox")
        self.tableWidget = QtWidgets.QTableWidget(Settings)
        self.tableWidget.setGeometry(QtCore.QRect(10, 10, 311, 311))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(Settings)
        self.doubleSpinBox.setGeometry(QtCore.QRect(130, 330, 61, 31))
        self.doubleSpinBox.setMinimum(0.5)
        self.doubleSpinBox.setMaximum(0.9)
        self.doubleSpinBox.setSingleStep(0.01)
        self.doubleSpinBox.setValue(0.71)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.label = QtWidgets.QLabel(Settings)
        self.label.setGeometry(QtCore.QRect(10, 330, 121, 31))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label.setText("Порог округления")
        self.checkBox = QtWidgets.QCheckBox(Settings)
        self.checkBox.setGeometry(QtCore.QRect(200, 330, 121, 31))
        self.checkBox.setObjectName("checkBox")
        self.checkBox.setText("Режим отладки")


